name: PR Check - Testes e Lint

on:
  pull_request:
    branches: ["**"]

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm ci

      - name: Rodar Linter
        run: |
          node --check src/index.js
          node --check src/formatter.js

      - name: Rodar Testes
        run: npm test
