name: Verificar Deploy no Render

on:
  workflow_dispatch:
  push:
    branches: ["master"]
jobs:
  check-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Aguardar estabilização (60s)
        run: sleep 60

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Verificar status da aplicação
        run: |
          npm ci
          node scripts/check-deploy.js
      - name: Verificar status da aplicação
        run: |
          npm ci
          node scripts/check-deploy.js



