name: Verificar Deploy no Render

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  check-render:
    runs-on: ubuntu-latest
    steps:
      - name: Esperar 45 segundos para estabilizar
        run: sleep 45
      - name: Fazer requisição ao app
        run: |
          status=$(curl -s -o /dev/null -w "%{http_code}" https://me-passa-a-cola.onrender.com/api-docs)
          if [ "$status" != "200" ]; then
            echo "Aplicação não respondeu como esperado"
            exit 1
          fi

